#![forbid(unsafe_code)]

//! Protobuf wire parity against the upstream C++ protobuf encoder.
//! Every expected byte comes from `fixtures/wire.json`, generated by linking
//! the real upstream generated `*.pb.cc` against libprotobuf.

use et_core::proto as et;
use std::collections::HashMap;

fn fixtures() -> HashMap<String, Vec<u8>> {
    let raw = include_str!("../../../fixtures/wire.json");
    let map: HashMap<String, String> = serde_json::from_str(raw).unwrap();
    map.into_iter()
        .map(|(k, v)| (k, hex::decode(&v).unwrap()))
        .collect()
}

fn enc<M: prost::Message>(m: &M) -> Vec<u8> {
    let mut buf = Vec::new();
    m.encode(&mut buf).unwrap();
    buf
}

#[test]
fn connect_request_minimal() {
    let f = fixtures();
    let r = et::ConnectRequest {
        client_id: Some("client-1".into()),
        version: Some(6),
        reset_intent: None,
        supports_challenge: None,
    };
    assert_eq!(enc(&r), *f.get("proto_connectrequest_minimal").unwrap());
}

#[test]
fn connect_request_empty_id_serializes_field() {
    let f = fixtures();
    let r = et::ConnectRequest {
        client_id: Some(String::new()),
        version: Some(6),
        reset_intent: None,
        supports_challenge: None,
    };
    assert_eq!(enc(&r), *f.get("proto_connectrequest_emptyid").unwrap());
}

#[test]
fn connect_response_statuses() {
    let f = fixtures();
    let s = |status| et::ConnectResponse {
        status: Some(status as i32),
        error: None,
        auth_challenge: None,
        reset_proof: None,
        reset_required: None,
        reset_salt: None,
    };
    assert_eq!(
        enc(&s(et::ConnectStatus::NewClient)),
        *f.get("proto_connectresponse_newclient_onlystatus").unwrap()
    );
    assert_eq!(
        enc(&et::ConnectResponse {
            status: Some(et::ConnectStatus::ReturningClient as i32),
            error: Some("ok".into()),
            auth_challenge: None,
            reset_proof: None,
            reset_required: None,
            reset_salt: None,
        }),
        *f.get("proto_connectresponse_returning_err").unwrap()
    );
    assert_eq!(
        enc(&s(et::ConnectStatus::InvalidKey)),
        *f.get("proto_connectresponse_invalidkey").unwrap()
    );
    assert_eq!(
        enc(&s(et::ConnectStatus::MismatchedProtocol)),
        *f.get("proto_connectresponse_mismatched").unwrap()
    );
}

#[test]
fn sequence_header_boundaries() {
    let f = fixtures();
    let h = |n| et::SequenceHeader {
        sequence_number: Some(n),
        reset: None,
        reset_salt: None,
    };
    assert_eq!(enc(&h(0)), *f.get("proto_sequenceheader_0").unwrap());
    assert_eq!(enc(&h(42)), *f.get("proto_sequenceheader_42").unwrap());
    assert_eq!(
        enc(&h(2147483647)),
        *f.get("proto_sequenceheader_int32max").unwrap()
    );
}

#[test]
fn catchup_buffer() {
    let f = fixtures();
    let c = et::CatchupBuffer {
        buffer: vec![b"aaa".to_vec(), b"bbbb".to_vec()],
    };
    assert_eq!(enc(&c), *f.get("proto_catchup_2bufs").unwrap());
    let c = et::CatchupBuffer { buffer: vec![] };
    assert_eq!(enc(&c), *f.get("proto_catchup_empty").unwrap());
}

#[test]
fn socket_endpoint() {
    let f = fixtures();
    let se = et::SocketEndpoint {
        name: Some("127.0.0.1".into()),
        port: Some(2022),
    };
    assert_eq!(enc(&se), *f.get("proto_socketendpoint_ipv4_port").unwrap());
    let se = et::SocketEndpoint {
        name: Some("/run/et.sock".into()),
        port: None,
    };
    assert_eq!(enc(&se), *f.get("proto_socketendpoint_unix").unwrap());
}

#[test]
fn flow_control_defaults_are_absent_and_wire_compatible() {
    let initial = et::InitialPayload::default();
    let term = et::TermInit::default();

    assert_eq!(initial.flowcontrol, None);
    assert_eq!(term.flowcontrol, None);
    assert!(enc(&initial).is_empty());
    assert!(enc(&term).is_empty());
}

#[test]
fn flow_control_opt_in_modes_use_additive_proto_fields() {
    let initial = et::InitialPayload {
        flowcontrol: Some(et::FlowControlMode::Backpressure as i32),
        ..Default::default()
    };
    let term = et::TermInit {
        flowcontrol: Some(et::FlowControlMode::Discard as i32),
        ..Default::default()
    };

    // Field 6/7/8 of InitialPayload are supports_exit_status, no_shell, and
    // disconnect_timeout_seconds. Flow control lives at field 9.
    // TermInit field 6 is hadreversetunnels and field 7 is the timeout, so
    // flow control lives at field 8.
    let fixtures = fixtures();
    // InitialPayload field 9 Backpressure: tag (9<<3)|0 = 0x48, value 1.
    assert_eq!(enc(&initial), [0x48, 0x01]);
    assert_eq!(
        enc(&initial),
        *fixtures
            .get("proto_initialpayload_flowcontrol_backpressure")
            .unwrap()
    );
    // TermInit field 8 Discard: tag (8<<3)|0 = 0x40, value 2.
    assert_eq!(enc(&term), [0x40, 0x02]);
    assert_eq!(
        enc(&term),
        *fixtures.get("proto_terminit_flowcontrol_discard").unwrap()
    );
}

#[test]
fn raw_pipe_fields_match_upstream_wire_bytes() {
    assert_eq!(et_core::PROTOCOL_VERSION, 6);
    let initial = et::InitialPayload {
        no_pty: Some(true),
        command: Some("id".to_owned()),
        ..Default::default()
    };
    let term = et::TermInit {
        no_pty: Some(true),
        command: Some("id".to_owned()),
        ..Default::default()
    };
    let stdout = et::TerminalBuffer {
        buffer: Some(b"hi".to_vec()),
        is_stderr: None,
    };
    let stderr = et::TerminalBuffer {
        buffer: Some(b"hi".to_vec()),
        is_stderr: Some(true),
    };

    // InitialPayload: field 4 bool true, field 5 string "id".
    assert_eq!(enc(&initial), [0x20, 0x01, 0x2a, 0x02, b'i', b'd']);
    // TermInit: field 3 bool true, field 4 string "id".
    assert_eq!(enc(&term), [0x18, 0x01, 0x22, 0x02, b'i', b'd']);
    assert_eq!(enc(&stdout), [0x0a, 0x02, b'h', b'i']);
    assert_eq!(enc(&stderr), [0x0a, 0x02, b'h', b'i', 0x10, 0x01]);
    assert!(enc(&et::InitialPayload::default()).is_empty());
    assert!(enc(&et::TermInit::default()).is_empty());
}

#[test]
fn port_forward_windows_use_additive_proto_fields() {
    let f = fixtures();
    let window = et::PortForwardWindow {
        bytes: Some(524_288),
        packets: Some(32),
    };
    let request = et::PortForwardDestinationRequest {
        destination: None,
        fd: Some(7),
        window: Some(window),
    };
    let response = et::PortForwardDestinationResponse {
        clientfd: Some(7),
        socketid: Some(9),
        error: None,
        window: Some(window),
    };
    let credit = et::PortForwardData {
        sourcetodestination: Some(true),
        socketid: Some(9),
        buffer: None,
        error: None,
        closed: None,
        half_close: None,
        window: Some(et::PortForwardWindow {
            bytes: Some(131_072),
            packets: Some(8),
        }),
    };

    assert_eq!(
        enc(&request),
        *f.get("proto_portforward_request_window").unwrap()
    );
    assert_eq!(
        enc(&response),
        *f.get("proto_portforward_response_window").unwrap()
    );
    assert_eq!(enc(&credit), *f.get("proto_portforward_credit").unwrap());
}

#[test]
fn upstream_exit_status_and_stdio_fields_use_upstream_tags() {
    assert_eq!(et_core::PROTOCOL_VERSION, 6);
    assert_eq!(et::TerminalPacketType::TerminalExitStatus as i32, 12);

    let initial = et::InitialPayload {
        supports_exit_status: Some(true),
        no_shell: Some(true),
        ..Default::default()
    };
    // Field 6 bool true, field 7 bool true.
    assert_eq!(enc(&initial), [0x30, 0x01, 0x38, 0x01]);

    let term = et::TermInit {
        no_shell: Some(true),
        ..Default::default()
    };
    // Field 5 bool true. Must not be the old flow-control tag for Discard.
    assert_eq!(enc(&term), [0x28, 0x01]);

    let status = et::TerminalExitStatus {
        exitcode: Some(143),
    };
    assert_eq!(enc(&status), [0x08, 0x8f, 0x01]);

    let half = et::PortForwardData {
        socketid: Some(3),
        closed: Some(true),
        half_close: Some(true),
        ..Default::default()
    };
    // Field 2 varint 3, field 5 bool true, field 6 bool true.
    assert_eq!(enc(&half), [0x10, 0x03, 0x28, 0x01, 0x30, 0x01]);
}

#[test]
fn challenge_reset_and_session_fields_use_upstream_tags() {
    assert_eq!(et_core::PROTOCOL_VERSION, 6);
    assert_eq!(et::ConnectStatus::RetryLater as i32, 5);
    assert_eq!(et_core::SESSION_KILL_COMMAND_VERSION, 1);
    let fixtures = fixtures();
    let expect = |name: &str, encoded: &[u8]| {
        assert_eq!(
            fixtures.get(name).map(Vec::as_slice),
            Some(encoded),
            "{name}"
        );
    };

    let request = et::ConnectRequest {
        client_id: Some("client-1".into()),
        version: Some(6),
        reset_intent: Some(true),
        supports_challenge: Some(true),
    };
    // Existing minimal request bytes, then field 3 bool and field 4 bool.
    let request_bytes = [
        0x0a, 0x08, b'c', b'l', b'i', b'e', b'n', b't', b'-', b'1', 0x10, 0x06, 0x18, 0x01, 0x20,
        0x01,
    ];
    assert_eq!(enc(&request), request_bytes);
    expect("proto_connectrequest_challenge_reset", &request_bytes);

    let retry = et::ConnectResponse {
        status: Some(et::ConnectStatus::RetryLater as i32),
        ..Default::default()
    };
    assert_eq!(enc(&retry), [0x08, 0x05]);
    expect("proto_connectresponse_retry_later", &enc(&retry));

    let auth = et::ConnectAuth {
        proof: Some(vec![0xab, 0xcd]),
    };
    assert_eq!(enc(&auth), [0x0a, 0x02, 0xab, 0xcd]);
    expect("proto_connectauth_proof", &enc(&auth));

    let header = et::SequenceHeader {
        sequence_number: Some(0),
        reset: Some(true),
        reset_salt: Some(vec![0x11, 0x22]),
    };
    assert_eq!(
        enc(&header),
        [0x08, 0x00, 0x10, 0x01, 0x1a, 0x02, 0x11, 0x22]
    );
    expect("proto_sequenceheader_reset", &enc(&header));

    let initial = et::InitialPayload {
        disconnect_timeout_seconds: Some(30),
        ..Default::default()
    };
    // Field 8 int32 30: tag 0x40.
    assert_eq!(enc(&initial), [0x40, 0x1e]);
    expect("proto_initialpayload_disconnect_timeout", &enc(&initial));

    let term = et::TermInit {
        hadreversetunnels: Some(true),
        disconnect_timeout_seconds: Some(30),
        ..Default::default()
    };
    // Field 6 bool, field 7 int32 30.
    assert_eq!(enc(&term), [0x30, 0x01, 0x38, 0x1e]);
    expect("proto_terminit_resume_timeout", &enc(&term));

    let user = et::TerminalUserInfo {
        ptyactive: Some(true),
        hadreversetunnels: Some(true),
        disconnect_timeout_seconds: Some(30),
        ..Default::default()
    };
    assert_eq!(enc(&user), [0x30, 0x01, 0x38, 0x01, 0x40, 0x1e]);
    expect("proto_terminaluserinfo_resume", &enc(&user));

    let info = et::TerminalInfo {
        command: Some(et::terminal_info::Command::KillSession as i32),
        commandversion: Some(1),
        ..Default::default()
    };
    assert_eq!(enc(&info), [0x30, 0x01, 0x38, 0x01]);
    expect("proto_terminalinfo_kill_v1", &enc(&info));
}
