#![forbid(unsafe_code)]

//! Protobuf wire parity against the upstream C++ protobuf encoder.
//! Every expected byte comes from `fixtures/wire.json`, generated by linking
//! the real upstream generated `*.pb.cc` against libprotobuf.

use et_core::proto as et;
use std::collections::HashMap;

fn fixtures() -> HashMap<String, Vec<u8>> {
    let raw = include_str!("../../../fixtures/wire.json");
    let map: HashMap<String, String> = serde_json::from_str(raw).unwrap();
    map.into_iter()
        .map(|(k, v)| (k, hex::decode(&v).unwrap()))
        .collect()
}

fn enc<M: prost::Message>(m: &M) -> Vec<u8> {
    let mut buf = Vec::new();
    m.encode(&mut buf).unwrap();
    buf
}

#[test]
fn connect_request_minimal() {
    let f = fixtures();
    let r = et::ConnectRequest {
        client_id: Some("client-1".into()),
        version: Some(6),
    };
    assert_eq!(enc(&r), *f.get("proto_connectrequest_minimal").unwrap());
}

#[test]
fn connect_request_empty_id_serializes_field() {
    let f = fixtures();
    let r = et::ConnectRequest {
        client_id: Some(String::new()),
        version: Some(6),
    };
    assert_eq!(enc(&r), *f.get("proto_connectrequest_emptyid").unwrap());
}

#[test]
fn connect_response_statuses() {
    let f = fixtures();
    let s = |status| et::ConnectResponse {
        status: Some(status as i32),
        error: None,
    };
    assert_eq!(
        enc(&s(et::ConnectStatus::NewClient)),
        *f.get("proto_connectresponse_newclient_onlystatus").unwrap()
    );
    assert_eq!(
        enc(&et::ConnectResponse {
            status: Some(et::ConnectStatus::ReturningClient as i32),
            error: Some("ok".into()),
        }),
        *f.get("proto_connectresponse_returning_err").unwrap()
    );
    assert_eq!(
        enc(&s(et::ConnectStatus::InvalidKey)),
        *f.get("proto_connectresponse_invalidkey").unwrap()
    );
    assert_eq!(
        enc(&s(et::ConnectStatus::MismatchedProtocol)),
        *f.get("proto_connectresponse_mismatched").unwrap()
    );
}

#[test]
fn sequence_header_boundaries() {
    let f = fixtures();
    let h = |n| et::SequenceHeader {
        sequence_number: Some(n),
    };
    assert_eq!(enc(&h(0)), *f.get("proto_sequenceheader_0").unwrap());
    assert_eq!(enc(&h(42)), *f.get("proto_sequenceheader_42").unwrap());
    assert_eq!(
        enc(&h(2147483647)),
        *f.get("proto_sequenceheader_int32max").unwrap()
    );
}

#[test]
fn catchup_buffer() {
    let f = fixtures();
    let c = et::CatchupBuffer {
        buffer: vec![b"aaa".to_vec(), b"bbbb".to_vec()],
    };
    assert_eq!(enc(&c), *f.get("proto_catchup_2bufs").unwrap());
    let c = et::CatchupBuffer { buffer: vec![] };
    assert_eq!(enc(&c), *f.get("proto_catchup_empty").unwrap());
}

#[test]
fn socket_endpoint() {
    let f = fixtures();
    let se = et::SocketEndpoint {
        name: Some("127.0.0.1".into()),
        port: Some(2022),
    };
    assert_eq!(enc(&se), *f.get("proto_socketendpoint_ipv4_port").unwrap());
    let se = et::SocketEndpoint {
        name: Some("/run/et.sock".into()),
        port: None,
    };
    assert_eq!(enc(&se), *f.get("proto_socketendpoint_unix").unwrap());
}

#[test]
fn flow_control_defaults_are_absent_and_wire_compatible() {
    let initial = et::InitialPayload::default();
    let term = et::TermInit::default();

    assert_eq!(initial.flowcontrol, None);
    assert_eq!(term.flowcontrol, None);
    assert!(enc(&initial).is_empty());
    assert!(enc(&term).is_empty());
}

#[test]
fn flow_control_opt_in_modes_use_additive_proto_fields() {
    let initial = et::InitialPayload {
        flowcontrol: Some(et::FlowControlMode::Backpressure as i32),
        ..Default::default()
    };
    let term = et::TermInit {
        flowcontrol: Some(et::FlowControlMode::Discard as i32),
        ..Default::default()
    };

    assert_eq!(enc(&initial), [0x20, 0x01]);
    assert_eq!(enc(&term), [0x18, 0x02]);
}

#[test]
fn port_forward_windows_use_additive_proto_fields() {
    let f = fixtures();
    let window = et::PortForwardWindow {
        bytes: Some(524_288),
        packets: Some(32),
    };
    let request = et::PortForwardDestinationRequest {
        destination: None,
        fd: Some(7),
        window: Some(window),
    };
    let response = et::PortForwardDestinationResponse {
        clientfd: Some(7),
        socketid: Some(9),
        error: None,
        window: Some(window),
    };
    let credit = et::PortForwardData {
        sourcetodestination: Some(true),
        socketid: Some(9),
        buffer: None,
        error: None,
        closed: None,
        window: Some(et::PortForwardWindow {
            bytes: Some(131_072),
            packets: Some(8),
        }),
    };

    assert_eq!(
        enc(&request),
        *f.get("proto_portforward_request_window").unwrap()
    );
    assert_eq!(
        enc(&response),
        *f.get("proto_portforward_response_window").unwrap()
    );
    assert_eq!(enc(&credit), *f.get("proto_portforward_credit").unwrap());
}
