#!/usr/bin/env bash
# Generate the Homebrew formula for a released et.rs version.
# Usage: generate-formula.sh <version>  (e.g. 0.0.2)
# Writes the formula to stdout. Fetches per-target sha256 from the GitHub release.
set -euo pipefail

version="$1"
base="https://github.com/minpeter/et.rs/releases/download/et@${version}"

sha() {
  curl -fsSL "${base}/et-${version}-$1.tar.gz.sha256" | cut -d' ' -f1
}

mac_arm=$(sha aarch64-apple-darwin)
mac_intel=$(sha x86_64-apple-darwin)
linux_arm=$(sha aarch64-unknown-linux-musl)
linux_intel=$(sha x86_64-unknown-linux-musl)

cat <<EOF
# typed: false
# frozen_string_literal: true

# Generated by et.rs release automation. Do not edit by hand.
class EtRs < Formula
  desc "Single telemetry-free EternalTerminal binary (Rust port)"
  homepage "https://github.com/minpeter/et.rs"
  version "${version}"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "${base}/et-${version}-aarch64-apple-darwin.tar.gz"
      sha256 "${mac_arm}"
    end
    on_intel do
      url "${base}/et-${version}-x86_64-apple-darwin.tar.gz"
      sha256 "${mac_intel}"
    end
  end

  on_linux do
    on_arm do
      url "${base}/et-${version}-aarch64-unknown-linux-musl.tar.gz"
      sha256 "${linux_arm}"
    end
    on_intel do
      url "${base}/et-${version}-x86_64-unknown-linux-musl.tar.gz"
      sha256 "${linux_intel}"
    end
  end

  # Both install \`et\`, \`etserver\`, \`etterminal\`, \`htm\` and \`htmd\`.
  conflicts_with "et", because: "et.rs is a drop-in replacement for EternalTerminal"

  def install
    bin.install "et"
    %w[etserver etterminal htm htmd].each do |role|
      bin.install_symlink "et" => role
    end
  end

  test do
    assert_match "et version #{version}", shell_output("#{bin}/et --version")
  end
end
EOF
