[package]
name = "et-htm"
description = "Headless terminal multiplexer (htm/htmd) for et.rs."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
portable-pty = "0.9.0"
wasmi = { version = "=2.0.0", default-features = false, features = ["stable", "std", "validate", "portable-dispatch"] }
wasmi_core = { version = "=2.0.0", default-features = false, features = ["std"] }

[target.'cfg(any(target_os = "macos", windows))'.dependencies]
sysinfo = { version = "0.37.2", default-features = false, features = ["system"] }

[target.'cfg(unix)'.dependencies]
rustix = { version = "1.1.4", features = ["event", "process", "fs", "termios"] }

[target.'cfg(windows)'.dependencies]
et-net = { path = "../et-net" }
filedescriptor = "0.8.3"
